### ISSUE TITLE
get_data return None

### ISSUE THREAD

**Issue by Beforerr** [SciQLop/speasy#119]
### Description

Try to get Wind 3dp data but return nothing

### What I Did

```
start = "2019-04-09"
end = "2019-04-12"
timerange = [start, end]

data = spz.get_data(
    "cda/WI_PLSP_3DP/MOM.P.MAGF",
    timerange,    
)
data == None
```

**Comment by jeandet** [comment]
I don't understand yet why but it seems that the CDAWeb WS gets stuck with this request:
https://cdaweb.gsfc.nasa.gov/WS/cdasr/1/dataviews/sp_phys/datasets/WI_PLSP_3DP/data/20190408T120000Z,20190412T120000Z/MOM.P.MAGF?format=cdf

It's even weirder because doing the same request through the CDAWeb html form works.

**Comment by jeandet** [comment]
@Beforerr I got an answer from CDAWeb, they are upgrading the server so this might explain why it wasn't responding. It's responding now but I get the same behavior thn you, this is indeed a bug in Speasy because we have to handle the fact that [variables names are modified to be IDL compatible](https://cdaweb.gsfc.nasa.gov/WebServices/REST/#Get_Data_GET) I'll push a fix ASAP.

**Comment by Beforerr** [comment]
@jeandet Thank you for the quick fix! I love speasy!
