### ISSUE TITLE
How to speedup 'import speasy as spz' ?

### ISSUE THREAD

**Issue by RichardHitier** [SciQLop/speasy#56]
* Space Physics WebServices Client version: 1.0.2
* Python version: 3.8.10
* Operating System: Ubuntu 20.04.5 LTS

### Description
When I use speasy, of course I 'import speasy as spz'
But for tests purpose I run my module very often. 
Unfortunately the import line takes much time.

I know it is possible to cache the amda inventory.
Is there a way to allow caching for the whole speasy import ?

### What I Did

Read the doc.

**Comment by jeandet** [comment]
@RichardHitier , I agree that speasy import is still too slow. 
There is INVENTORIES/cache_retention_days setting but it is ignored when using speasy proxy which might be an issue after all.
I'll check if this speeds up speasy import.

**Comment by jeandet** [comment]
@RichardHitier can you try PR #57 and see if this is enough for your use case, you can use:

`pip install --upgrade git+https://github.com/jeandet/speasy@import_speedup` 

I think I took most of the low hanging fruits here, I don't think I can get much more speedups since inventories are quite big now and loading them takes quite some time anyway.
