### ISSUE TITLE
Can't get data from proxy server http://sciqlop.lpp.polytechnique.fr/cache

### ISSUE THREAD

**Issue by cmoissar** [SciQLop/speasy#69]
* Space Physics WebServices Client version:
* Python version: Python 3.10.6
* Operating System: Ubuntu 22.04.1 LTS

### Description

import speasy

### What I Did

Input:
import speasy

Output:
Can't get data from proxy server http://sciqlop.lpp.polytechnique.fr/cache

This is not a problem I had two weeks ago.

Best wishes,
Clement

**Comment by jeandet** [comment]
@cmoissar, lately we had DNS issues at Polytechnique I'm afraid, this might be related. Did you try to access  http://sciqlop.lpp.polytechnique.fr/cache from your browser? If it also fails then this is likely a DNS issue. One temporary fix can be to use http://129.104.27.10/cache instead (this IP is likely to remain the same for years).

**Comment by jeandet** [comment]
@cmoissar, using server IP, won't work sadly, I just figured out from the logs sorry :/

**Comment by cmoissar** [comment]
Accessing http://sciqlop.lpp.polytechnique.fr/cache from the browser doesn't work, as you expected.

Here's something I find confusing:
On my computer, I can still run my code. It takes a lot longer than it did a couple of weeks ago but still works.
One of my students cannot use his code at all. 
Yet both problems appeared at the same time.

Is there a way to skip the Polytechnique cache and download data directly from the different providers (cdaweb and co) without ditching speasy altogether?

Or is not worth trying because the Polytechnique servers will be back to normal soon?

Thanks for your help @jeandet!

**Comment by jeandet** [comment]
Ok, that's very unfortunate, we are investigating this DNS issue. The worst is that I can access 
 http://sciqlop.lpp.polytechnique.fr/cache from home it just seems to randomly fail on some DNS servers around the world..
In the mean time, you can disable the proxy server:

-  by editing your speasy config file.
On linux, you'll find it in `~/.config/speasy/config.ini`, then simply edit or add the following lines:
```ini
[PROXY]
enabled = False
url = http://sciqlop.lpp.polytechnique.fr/cache
```
  On others OS, you can find the location with the following python code (I don't remember their location):
```Python
import appdirs
print(appdirs.user_config_dir( appname="speasy", appauthor="LPP") + "/config.ini")
```

- or, you can set SPEASY_PROXY_ENABLED environment variable to "false" before you import speasy like this:

```Python
import os
os.environ['SPEASY_PROXY_ENABLED'] = 'false'
import speasy as spz
```

Note that once the proxy is disabled, speasy will take little longer to load and will print a lot of warnings like `Non compliant ISTP file: variable V_thermal has LABL_PTR_1 attribute which points to a variable which does not exist`. You will get these warnings because you are building CDA inventory locally and speasy has to parse a lot of partly compliant CDF/ISTP files.

**Comment by jeandet** [comment]
for the record https://dnschecker.org/#A/lpp.polytechnique.fr
![image](https://user-images.githubusercontent.com/7570249/199288486-f07950fc-e75e-4244-8858-20972501483e.png)

**Comment by jeandet** [comment]
@cmoissar, the DNS issue seems resolved now 🤞.
